// Build a SUBSET of the RemixIcon font containing only the glyphs this app
// actually uses. The full RemixIcon ships ~2,800 icons (189 KB woff2 + 157 KB
// CSS); we use ~70. Subsetting cuts the icon payload to ~10 KB — the single
// biggest first-load win for the public/client pages on mobile.
//
// What it does:
//   1. Scans src/**/*.{svelte,ts} for `ri-*` class names actually referenced.
//   2. Reads the codepoint for each from the upstream remixicon.css.
//   3. Emits a subset woff2 (static/fonts/remixicon-subset.woff2) via subset-font.
//   4. Emits a tiny CSS (src/lib/styles/remixicon.css) with only those classes.
//
// Re-run whenever you add/remove an icon:  npm run build:icons
// (also wired into `prebuild` so production builds always ship a fresh subset).

import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import subsetFont from 'subset-font';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = join(root, 'src');
const UPSTREAM_CSS = join(root, 'node_modules', 'remixicon', 'fonts', 'remixicon.css');
const UPSTREAM_WOFF2 = join(root, 'node_modules', 'remixicon', 'fonts', 'remixicon.woff2');
const OUT_WOFF2 = join(root, 'static', 'fonts', 'remixicon-subset.woff2');
const OUT_CSS = join(root, 'src', 'lib', 'styles', 'remixicon.css');

// --- 1. Collect every `ri-*` class referenced in source ---------------------
function walk(dir, acc = []) {
	for (const name of readdirSync(dir)) {
		if (name === 'node_modules' || name.startsWith('.')) continue;
		const p = join(dir, name);
		const s = statSync(p);
		if (s.isDirectory()) walk(p, acc);
		else if (/\.(svelte|ts|js)$/.test(name)) acc.push(p);
	}
	return acc;
}

const used = new Set();
for (const file of walk(SRC)) {
	const text = readFileSync(file, 'utf8');
	for (const m of text.matchAll(/\bri-[a-z0-9-]+/g)) used.add(m[0]);
}

// --- 2. Map class name -> codepoint from the upstream CSS -------------------
// Lines look like:  .ri-focus-3-line:before { content: "\ed4c"; }
const css = readFileSync(UPSTREAM_CSS, 'utf8');
const codepoints = new Map(); // name -> "\ed4c"
for (const m of css.matchAll(/\.(ri-[a-z0-9-]+):before\s*\{\s*content:\s*"(\\[0-9a-fA-F]+)"/g)) {
	codepoints.set(m[1], m[2]);
}

// Size helpers (.ri-lg etc.) have no glyph — keep them out of the glyph set but
// preserve their CSS rules verbatim so existing markup keeps working.
const sizeHelpers = [...css.matchAll(/\.(ri-(?:lg|xl|xxs|xs|sm|[1-7]x|fw))\s*\{[^}]*\}/g)].map(
	(m) => m[0]
);

const iconRules = [];
const glyphChars = [];
const missing = [];
for (const name of [...used].sort()) {
	const cp = codepoints.get(name);
	if (!cp) {
		// Not a real icon (e.g. a size helper caught above, or a typo) — skip glyph.
		if (!/^ri-(lg|xl|xxs|xs|sm|[1-7]x|fw)$/.test(name)) missing.push(name);
		continue;
	}
	iconRules.push(`.${name}:before{content:"${cp}"}`);
	glyphChars.push(String.fromCodePoint(parseInt(cp.slice(1), 16)));
}

if (missing.length) {
	console.warn(`[icons] ${missing.length} unknown ri-* class(es) ignored:`, missing.join(', '));
}

// --- 3. Subset the woff2 to just the used glyphs ---------------------------
const subset = await subsetFont(readFileSync(UPSTREAM_WOFF2), glyphChars.join(''), {
	targetFormat: 'woff2'
});
writeFileSync(OUT_WOFF2, subset);

// --- 4. Emit the tiny CSS --------------------------------------------------
const out = `/* AUTO-GENERATED by scripts/build-icons.mjs — do not edit.
 * RemixIcon v4.9.1 subset: ${iconRules.length} of ~2800 glyphs actually used.
 * Regenerate with: npm run build:icons */
@font-face {
  font-family: 'remixicon';
  src: url('/fonts/remixicon-subset.woff2') format('woff2');
  font-display: swap;
  font-style: normal;
  font-weight: normal;
}
[class^="ri-"], [class*=" ri-"] {
  font-family: 'remixicon' !important;
  font-style: normal;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
${sizeHelpers.join('\n')}
${iconRules.join('\n')}
`;
writeFileSync(OUT_CSS, out);

const kb = (n) => (n / 1024).toFixed(1);
console.log(
	`[icons] subset ${iconRules.length} glyphs → ${kb(subset.length)} KB woff2` +
		` (from ${kb(statSync(UPSTREAM_WOFF2).size)} KB), CSS ${kb(Buffer.byteLength(out))} KB`
);
